import { siteUrl, stripBase } from './paths';
import { useEffect, useMemo, useState } from 'react';
import { GuideCover, CoverCredit } from './components/GuideCover';
import { MediaCaption } from './components/MediaCaption';
import { DayRouteMap } from './components/DayRouteMap';
import { EgyptMap } from './components/EgyptMap';
import { GuideSpatial } from './components/GuideSpatial';
import { SiteNav } from './components/SiteNav';
import { cityBySlug, cityProfiles } from './data/cities';
import { guideBySlug, guideCatalog } from './data/guides';
import { allItems, bookings, knownConflicts, tripDays } from './data/journey';
import { hasInteractiveNodeBinding } from './data/spatial-delivery';
import { sourceById } from './data/sources';
import { exteriorCatalog } from './data/exteriors/catalog';
import type { CulturalGuide, GuideHighlight } from './data/types';

function Footer() { return <footer className="footer"><p>独立中文文化导览 · 不代表场馆、文物部门、航空公司、酒店或运营商</p><p>事实核对：2026-09-16 · 私人订单原件未收录</p></footer>; }
function Status({ value }: { value: string }) { return <span className={`status status--${value}`}>{value}</span>; }
function spatialDeliveryLabel(guide: CulturalGuide) { if (guide.spatial.mode === 'interactive-schematic') return '可交互 2D／3D 建筑模型'; if (guide.spatial.mode === 'official-plan-reference') return `${guide.spatial.referenceImages?.length ?? 0} 张已审核验图件`; if (guide.spatial.mode === 'spatial-index') return '证据不足 · 文字空间索引'; return '空间资料明确省略'; }

function HomePage() {
  const pending = allItems.filter((item) => item.status === '待确认').length;
  return <main><SiteNav active="home"/><section className="home-hero"><img src={siteUrl("/images/giza/giza-panorama.jpg")} alt="吉萨高地三座主要金字塔全景"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">CAIRO · NUBIA · THEBES · RED SEA</p><h1>埃及纪行<br/><em>2026</em></h1><p>从文明博物馆与吉萨进入古代国家，再沿尼罗河理解努比亚与底比斯，最后转向红海生态。行程事实与文化导览分层，日期未定不阻塞景点内容。</p><div className="hero-stats"><span><strong>12</strong> 日</span><span><strong>{guideCatalog.length}</strong> 个景点章节</span><span><strong>4</strong> 个城市文化章节</span></div></div><a className="hero-cta" href={siteUrl("/guides/")}>浏览全部景点 <span>↗</span></a></section>
    <section className="content-band intro-statement"><p className="eyebrow">Production guide</p><h2>埃及文化旅程</h2><p>全国地图用于理解跨城顺序；逐日地图只连接已排主线；每个景点分别说明外观／抵达与内部／场内参观。14 个景点接入原生空间图：室内厅室、遗址总图与室外街区使用各自核对的来源；2D 与 3D 共享空间数据。剖切高度、历史布局和现时开放的区别在各图内列明。</p></section>
    <EgyptMap/>
    <section className="content-band coverage"><header className="section-heading"><p className="eyebrow">Guide coverage</p><h2>所有正式景点都有原生导览</h2><p>博物馆、考古遗址、历史街区与红海体验按证据等级选择地图精度。</p></header><div className="coverage-grid">{guideCatalog.map((guide) => <a key={guide.slug} href={siteUrl(`/guides/${guide.slug}/`)}><GuideCover media={guide.hero} role="card"/><div><small>{guide.city} · {guide.category}</small><h3>{guide.title}</h3><p>{guide.deck}</p><span>{guide.highlights.length} 条现场解读 · {spatialDeliveryLabel(guide)}</span></div></a>)}</div></section>
    <section className="audit-band"><div><p className="eyebrow">Known state</p><h2>确定的先完成，不确定的保持可见</h2></div><div className="audit-grid"><article><strong>{bookings.length}</strong><span>已核对凭证记录</span></article><article><strong>{pending}</strong><span>待确认行程项目</span></article><article><strong>{knownConflicts.length}</strong><span>明确时间/交通冲突</span></article><article><strong>{guideCatalog.length}</strong><span>已建立景点章节</span></article></div><a href={siteUrl("/bookings/")}>查看凭证边界与待确认 →</a></section><Footer/></main>;
}

function ItineraryPage() {
  const [filter, setFilter] = useState('全部');
  const group = (region: string) => region.includes('开罗') || region.includes('吉萨') ? '开罗 / 吉萨' : region.includes('阿斯旺') || region.includes('阿布辛贝') ? '阿斯旺 / 努比亚' : region.includes('卢克索') ? '卢克索' : region.includes('红海') || region.includes('赫尔格达') ? '红海' : '国际交通';
  const regions = ['全部', ...new Set(tripDays.map((day) => group(day.region)))]; const visible = filter === '全部' ? tripDays : tripDays.filter((day) => group(day.region) === filter);
  return <main className="subpage"><SiteNav active="itinerary"/><header className="page-intro"><p className="eyebrow">Source-faithful itinerary</p><h1>逐日行程与路线地图</h1><p>截图优先于草表；当日主项保持原顺序，备选项统一置底且不进入连线。休息与未定位项目保留在行程中，不绘制为地图路线。</p></header><div className="filters">{regions.map((region) => <button type="button" key={region} className={filter === region ? 'active' : ''} aria-pressed={filter === region} onClick={() => setFilter(region)}>{region}</button>)}</div><div className="timeline">{visible.map((day) => { const scheduled = day.items.filter((item) => item.status !== '备选'); const alternatives = day.items.filter((item) => item.status === '备选'); return <section className="day" key={day.id}><header><time dateTime={day.date}>{day.label}</time><div><small>{day.region}</small><h2>{day.summary}</h2></div></header><DayRouteMap day={day}/><div className="day-items">{[...scheduled, ...alternatives].map((item) => <article id={item.id} className={`timeline-item ${item.status === '备选' ? 'alternative' : ''}`} key={item.id}><div className="time">{item.time}</div><div><div className="item-heading"><h3>{item.title}</h3><Status value={item.status}/></div>{item.arrival && <p className="arrival">到达说明｜{item.arrival}</p>}{item.note && <p>{item.note}</p>}{item.conflict && <p className="conflict">待核对｜{item.conflict}</p>}{item.guideSlug && <a className="text-link" href={siteUrl(`/guides/${item.guideSlug}/`)}>打开景点导览 →</a>}</div></article>)}</div></section>; })}</div><Footer/></main>;
}

function CitiesPage() { return <main className="subpage"><SiteNav active="cities"/><header className="page-intro"><p className="eyebrow">City culture</p><h1>城市与文化地景</h1><p>把独立景点重新放回城市、河流、宗教仪式与现代遗产管理中。</p></header><div className="city-grid">{cityProfiles.map((city) => <a href={siteUrl(`/cities/${city.slug}/`)} key={city.slug}><img src={siteUrl(city.hero.src)} alt={city.hero.alt}/><div><small>{city.region}</small><h2>{city.name}</h2><p>{city.thesis}</p><span>{city.guideSlugs.length} 个导览 →</span></div></a>)}</div><Footer/></main>; }

function CityPage({ slug }: { slug: string }) {
  const city = cityBySlug.get(slug); if (!city) return <NotFound/>;
  const guides = city.guideSlugs.map((guideSlug) => guideBySlug.get(guideSlug)).filter(Boolean) as CulturalGuide[];
  return <main className="subpage"><SiteNav active="cities"/><header className="city-hero"><img src={siteUrl(city.hero.src)} alt={city.hero.alt}/><div className="hero-shade"/><div><p className="eyebrow">{city.region}</p><h1>{city.name}</h1><p>{city.originalName}</p><strong>{city.thesis}</strong></div></header><section className="content-band chronology"><header><p className="eyebrow">Long durée</p><h2>三段时间，读懂这座地方</h2></header><div>{city.chronology.map((item) => <article key={item.period}><span>{item.period}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section><section className="content-band"><header className="section-heading"><p className="eyebrow">Native guides</p><h2>{city.name}的独立景点</h2></header><div className="guide-list">{guides.map((guide) => <a key={guide.slug} href={siteUrl(`/guides/${guide.slug}/`)}><GuideCover media={guide.hero} role="thumbnail"/><div><small>{guide.category}</small><h3>{guide.title}</h3><p>{guide.deck}</p></div></a>)}</div></section><Footer/></main>;
}

function GuidesPage() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('全部');
  const visible = guideCatalog.filter((guide) => (category === '全部' || guide.category === category) && `${guide.title}${guide.originalTitle}${guide.city}${guide.tags.join('')}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <main className="subpage"><SiteNav active="guides"/><header className="page-intro"><p className="eyebrow">Guide directory</p><h1>景点导览目录</h1><p>正式排期的 14 个独立文化与自然景点均已建立原生导览，可按城市、类型或主题直接检索。</p></header><section className="directory-tools"><label><span>搜索景点、城市或主题</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="例如：柱厅、木乃伊、红海"/></label><div className="filters">{['全部', '博物馆', '考古遗址', '历史城区', '自然体验'].map((item) => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)} type="button">{item}</button>)}</div></section><div className="guide-directory">{visible.map((guide) => <a href={siteUrl(`/guides/${guide.slug}/`)} key={guide.slug}><GuideCover media={guide.hero} role="directory"/><div><p className="eyebrow">{guide.city} · {guide.category}</p><h2>{guide.title}</h2><p>{guide.deck}</p><ul><li>外观／抵达与内部／场内分章</li><li>{guide.highlights.length} 条完整对象解读</li><li>{spatialDeliveryLabel(guide)}</li><li>现场顺序、实用核对与来源清单</li></ul><span>打开导览 →</span></div></a>)}</div>{!visible.length && <div className="empty-state"><strong>没有匹配结果</strong><p>清空搜索或切换分类。</p></div>}<Footer/></main>;
}

function ImageViewer({ item, onClose }: { item: GuideHighlight; onClose: () => void }) { useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; addEventListener('keydown', close); return () => removeEventListener('keydown', close); }, [onClose]); return <div className="lightbox" role="dialog" aria-modal="true" aria-label={`${item.title}图片查看`} onClick={onClose}><button type="button" onClick={onClose}>关闭 ×</button><figure onClick={(event) => event.stopPropagation()}><img src={siteUrl(item.image.src)} alt={item.image.alt}/><figcaption><strong>{item.title}</strong><p><MediaCaption media={item.image}/></p></figcaption></figure></div>; }

function GuidePage({ guide }: { guide: CulturalGuide }) {
  const [locateRequest,setLocateRequest]=useState(0);
  const initial = location.hash.startsWith('#object-') ? location.hash.replace('#object-', '') : ''; const firstNode = guide.spatial.architecture?.entry.status === 'mapped' ? guide.spatial.architecture.entry.spaceId : guide.spatial.nodes[0]?.id ?? ''; const [selectedId, setSelectedId] = useState(firstNode); const [query, setQuery] = useState(''); const [onsite, setOnsite] = useState(false); const [activeStep, setActiveStep] = useState(0); const [viewer, setViewer] = useState<GuideHighlight | null>(null);
  const visible = useMemo(() => guide.highlights.filter((item) => `${item.title}${item.summary}${item.lookFor}`.toLowerCase().includes(query.trim().toLowerCase())), [guide, query]);
  const onsiteSteps = useMemo(() => [
    ...guide.visitChapters.map((chapter) => ({
      nodeId: undefined,
      title: `${chapter.label}｜${chapter.title}`,
      body: `${chapter.summary} 现场顺序：${chapter.checkpoints.join(' ')} 进入边界：${chapter.accessNote}`,
    })),
    ...guide.sequence,
  ], [guide]);
  useEffect(() => { const id = initial ? `object-${initial}` : location.hash.slice(1); if (!id) return; const frame = requestAnimationFrame(() => document.getElementById(id)?.scrollIntoView()); return () => cancelAnimationFrame(frame); }, [guide.slug, initial]);
  const sources = [...new Set([...guide.sourceIds, ...guide.visitChapters.flatMap((chapter) => chapter.sourceIds), ...guide.spatial.sourceIds, ...(guide.spatial.referenceImages?.map((item) => item.sourceId) ?? []), ...(exteriorCatalog[guide.slug]?.models.flatMap(m=>m.sourceIds)??[])])].map((id) => sourceById.get(id)).filter(Boolean);
  if (onsite) { const step = onsiteSteps[activeStep]; return <main className="onsite-mode"><header><button type="button" onClick={() => setOnsite(false)}>← 退出现场模式</button><span>{activeStep + 1} / {onsiteSteps.length}</span></header><section><p className="eyebrow">{guide.title}</p><h1>{step.title}</h1><p>{step.body}</p>{step.nodeId && <button type="button" onClick={() => { setOnsite(false); setSelectedId(step.nodeId!); setTimeout(() => document.getElementById('spatial')?.scrollIntoView(), 0); }}>查看空间资料</button>}</section><footer><button type="button" disabled={activeStep === 0} onClick={() => setActiveStep((value) => value - 1)}>上一步</button><button type="button" disabled={activeStep === onsiteSteps.length - 1} onClick={() => setActiveStep((value) => value + 1)}>下一步</button></footer></main>; }
  return <main className="guide-page"><SiteNav active="guides"/><section className="guide-hero"><GuideCover media={guide.hero} role="hero"/><div className="hero-shade"/><div><p className="eyebrow">{guide.city} · {guide.category} · {guide.tier === 'major' ? '重点章节' : '完整章节'}</p><h1>{guide.title}</h1><p className="original-title">{guide.originalTitle}</p><p>{guide.deck}</p><div className="guide-hero-actions"><a href="#orientation">开始阅读 ↓</a><button type="button" onClick={() => { setActiveStep(0); setOnsite(true); }}>进入现场模式</button></div></div></section>
    <nav className="chapter-nav" aria-label="本章目录"><a href="#orientation">定位</a><a href="#visit-scope">外观／内部</a><a href="#spatial">空间</a><a href="#sequence">顺序</a><a href="#highlights">解读</a><a href="#practical">实用</a><a href="#sources">来源</a></nav>
    <section className="guide-overview content-band" id="orientation"><div><p className="eyebrow">Orientation</p><h2>先知道自己在看什么</h2><p>{guide.overview}</p></div><div className="orientation-grid">{guide.orientation.map((item, index) => <article key={item.title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
    <section className="visit-scope content-band" id="visit-scope"><header className="section-heading"><p className="eyebrow">Exterior & interior</p><h2>先看外观，再进入内部</h2><p>把抵达、建筑外部和内部／场内参观分开；没有室内空间的景点明确说明，不用虚构建筑内部。</p></header><div className="visit-chapter-grid">{guide.visitChapters.map((chapter) => <article key={chapter.id} id={`visit-${chapter.id}`}><figure><img src={siteUrl(chapter.image.src)} alt={chapter.image.alt} loading="lazy"/><figcaption><MediaCaption media={chapter.image}/></figcaption></figure><div><p className="eyebrow">{chapter.label}</p><h3>{chapter.title}</h3><p>{chapter.summary}</p><h4>现场按这几步看</h4><ol>{chapter.checkpoints.map((checkpoint) => <li key={checkpoint}>{checkpoint}</li>)}</ol><p className="access-note"><strong>进入边界</strong>{chapter.accessNote}</p></div></article>)}</div></section>
    <GuideSpatial guide={guide} selectedId={selectedId} onSelect={setSelectedId} locateRequest={locateRequest}/>
    <section className="sequence-band" id="sequence"><header className="section-heading"><p className="eyebrow">Interpretive sequence</p><h2>现场顺序，不冒充导航</h2><p>按理解递进组织；入口、开放与真实走法服从现场。</p></header><div className="sequence-list">{guide.sequence.map((item, index) => <button type="button" key={`${item.title}-${index}`} className={item.nodeId === selectedId ? 'active' : ''} onClick={() => { if (item.nodeId) { setSelectedId(item.nodeId); setLocateRequest(n=>n+1); } document.getElementById('spatial')?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); }}><strong>{item.title}</strong><span>{item.body}</span></button>)}</div></section>
    <section className="highlights content-band" id="highlights"><header className="section-heading"><p className="eyebrow">Field notes</p><h2>{guide.highlights.length} 条对象级现场解读</h2><label className="search"><span>搜索本章</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索对象、空间或观察方法"/></label></header><div className="highlight-grid">{visible.map((item) => <article key={item.id} id={`object-${item.id}`}><button type="button" className="image-button" onClick={() => setViewer(item)} aria-label={`放大${item.title}图片`}><img src={siteUrl(item.image.src)} alt={item.image.alt} loading="lazy"/></button><div><p className="eyebrow">{item.location} · {item.period}</p><h3>{item.title}</h3><p>{item.summary}</p><h4>为什么重要</h4><p>{item.whyItMatters}</p><h4>现场看什么</h4><p>{item.lookFor}</p><div className="object-actions">{hasInteractiveNodeBinding(guide.spatial, item.nodeId) && <button type="button" onClick={() => { setSelectedId(item.nodeId!); setLocateRequest(n=>n+1); document.getElementById('spatial')?.scrollIntoView(); }}>在景点地图中定位 ↑</button>}<a href={siteUrl(`#object-${item.id}`)}>复制深链接 #</a></div><small><MediaCaption media={item.image}/></small></div></article>)}</div></section>
    <section className="practical-band" id="practical"><header><p className="eyebrow">Practical / checked 2026-09-16</p><h2>临行前必须再核对</h2></header><ol>{guide.practical.map((item) => <li key={item}>{item}</li>)}</ol><p className="evidence-note">空间交付：{spatialDeliveryLabel(guide)}。{guide.spatial.evidenceNote}</p></section>
    <section className="sources-band" id="sources"><header><p className="eyebrow">Sources & integrity</p><h2>本章使用的公开来源</h2></header><div>{sources.map((source) => <article key={source!.id}><strong>{source!.title}</strong><span>{source!.publisher} · {source!.authority}</span>{source!.url ? <a href={siteUrl(source!.url)} target="_blank" rel="noreferrer">打开原始页面 ↗</a> : <small>{source!.note}</small>}</article>)}</div><CoverCredit media={guide.hero}/><p>本地媒体逐图授权记录：<a href={siteUrl("/images/guides/media-manifest.json")} target="_blank" rel="noreferrer">media-manifest.json</a></p></section>{viewer && <ImageViewer item={viewer} onClose={() => setViewer(null)}/>}<Footer/></main>;
}

function BookingsPage() { const categories = ['交通', '住宿', '门票'] as const; return <main className="subpage"><SiteNav active="bookings"/><header className="page-intro"><p className="eyebrow">Evidence state</p><h1>凭证与待确认</h1><p>预订状态和原始凭证核对分开显示；页面不展示金额、订单号、旅客身份或私人截图。</p></header><section className="pending-panel"><h2>优先待确认</h2><ol><li>实际人数：草表出现“4人打车”，酒店截图仅能证明房型，不能据此确定人数。</li><li>10月1日至3日开罗酒店名称、地址与入住确认。</li><li>10月10日赫尔格达返回开罗选择包车还是航班，以及与 10月11日 02:45 航班的衔接。</li><li>门票、包车、红海运营商及潜水项目；预算、饮食、步行与潜水偏好。</li><li>视觉已按用户本轮要求统一继承欧洲行蓝金体系；这不等于携带欧洲行订单或私人数据。</li></ol></section><div className="booking-sections">{categories.map((category) => <section key={category}><header><p className="eyebrow">{category}</p><h2>{category}记录</h2></header>{bookings.filter((item) => item.category === category).length ? <div className="booking-list">{bookings.filter((item) => item.category === category).map((item) => <article key={item.id}><div><small>{item.date}</small><h3>{item.title}</h3>{item.note && <p>{item.note}</p>}</div><div><Status value={item.status}/><small>{item.evidenceState}</small></div></article>)}</div> : <div className="empty-state"><strong>尚未提供门票凭证</strong><p>景点资料与空间模型继续核验；行程状态仍保持待确认。</p></div>}</section>)}</div><section className="conflict-list"><header><p className="eyebrow">Conflicts</p><h2>不能静默合并的差异</h2></header>{knownConflicts.map((item) => <article key={item.itemId}><strong>{item.day}</strong><p>{item.conflict}</p></article>)}</section><Footer/></main>; }

function NotFound() { return <main className="subpage"><SiteNav/><section className="not-found"><p className="eyebrow">404</p><h1>这个页面不存在</h1><p>没有任何导航项被错误标成当前页。</p><a href={siteUrl("/")}>返回旅程总览</a></section></main>; }

function getPage(path: string) { const normalized = path.replace(/index\.html$/, '').replace(/\/+$/, '') || '/'; if (normalized === '/') return <HomePage/>; if (normalized === '/itinerary') return <ItineraryPage/>; if (normalized === '/cities') return <CitiesPage/>; if (normalized.startsWith('/cities/')) return <CityPage slug={normalized.split('/')[2]}/>; if (normalized === '/guides') return <GuidesPage/>; if (normalized.startsWith('/guides/')) { const guide = guideBySlug.get(normalized.split('/')[2]); return guide ? <GuidePage key={guide.slug} guide={guide}/> : <NotFound/>; } if (normalized === '/bookings') return <BookingsPage/>; return <NotFound/>; }

export default function App() { const [path, setPath] = useState(location.pathname); useEffect(() => { const onClick = (event: MouseEvent) => { const anchor = (event.target as Element).closest('a'); if (!anchor || anchor.origin !== location.origin || anchor.target || event.metaKey || event.ctrlKey || event.shiftKey || anchor.hasAttribute('download')) return; if (anchor.hash && anchor.pathname === location.pathname) return; event.preventDefault(); history.pushState({}, '', anchor.href); setPath(location.pathname); scrollTo({ top: 0, behavior: 'auto' }); }; const onPop = () => setPath(location.pathname); document.addEventListener('click', onClick); addEventListener('popstate', onPop); return () => { document.removeEventListener('click', onClick); removeEventListener('popstate', onPop); }; }, []); return getPage(stripBase(path)); }
