import { useEffect, useMemo, useState } from 'react';
import { GuideCover, CoverCredit } from './components/GuideCover';
import { ArchitectureMap as GuideSpatial } from './components/ArchitectureMap';
import { SiteNav } from './components/SiteNav';
import { sourceById } from './data/sources';
import { exteriorCatalog } from './data/exteriors/catalog';
import { assetUrl } from './paths';
import type { CulturalGuide, GuideHighlight, SpatialModel } from './data/types';
function hasInteractiveNodeBinding(model:SpatialModel,id?:string){return !!id && model.nodes.some(n=>n.id===id&&n.renderBindings);}
function spatialDeliveryLabel(_guide:CulturalGuide){return '可交互 2D／3D 建筑模型';}
function Footer(){return <footer className="footer"><p>埃及国家文明博物馆 · 独立中文导览，非馆方官方网站</p><p>开放安排以馆方当日公告为准 · 图片与空间资料来源见本章说明</p></footer>;}
function ImageViewer({ item, onClose }: { item: GuideHighlight; onClose: () => void }) { useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; addEventListener('keydown', close); return () => removeEventListener('keydown', close); }, [onClose]); return <div className="lightbox" role="dialog" aria-modal="true" aria-label={`${item.title}图片查看`} onClick={onClose}><button type="button" onClick={onClose}>关闭 ×</button><figure onClick={(event) => event.stopPropagation()}><img src={item.image.src} alt={item.image.alt}/><figcaption><strong>{item.title}</strong><p>{item.image.caption}</p></figcaption></figure></div>; }

export function GuidePage({ guide }: { guide: CulturalGuide }) {
  const [locateRequest,setLocateRequest]=useState(0);
  const initial = location.hash.startsWith('#object-') ? location.hash.replace('#object-', '') : ''; const firstNode = guide.spatial.architecture?.entry.status === 'mapped' ? guide.spatial.architecture.entry.spaceId : guide.spatial.nodes[0]?.id ?? ''; const [selectedId, setSelectedId] = useState(firstNode); const [query, setQuery] = useState(''); const [onsite, setOnsite] = useState(false); const [activeStep, setActiveStep] = useState(0); const [viewer, setViewer] = useState<GuideHighlight | null>(null);
  const visible = useMemo(() => guide.highlights.filter((item) => `${item.title}${item.summary}${item.lookFor}`.toLowerCase().includes(query.trim().toLowerCase())), [guide, query]);
  const onsiteSteps = useMemo(() => [
    ...guide.visitChapters.map((chapter) => ({
      nodeId: undefined,
      title: `${chapter.label}｜${chapter.title}`,
      body: `${chapter.summary} 现场顺序：${chapter.checkpoints.join(' ')} 进入边界：${chapter.accessNote}`,
    })),
    ...guide.sequence,
  ], [guide]);
  useEffect(() => { const id = initial ? `object-${initial}` : location.hash.slice(1); if (!id) return; const frame = requestAnimationFrame(() => document.getElementById(id)?.scrollIntoView()); return () => cancelAnimationFrame(frame); }, [guide.slug, initial]);
  const sources = [...new Set([...guide.sourceIds, ...guide.visitChapters.flatMap((chapter) => chapter.sourceIds), ...guide.spatial.sourceIds, ...(guide.spatial.referenceImages?.map((item) => item.sourceId) ?? []), ...(exteriorCatalog[guide.slug]?.models.flatMap(m=>m.sourceIds)??[])])].map((id) => sourceById.get(id)).filter(Boolean);
  if (onsite) { const step = onsiteSteps[activeStep]; return <main className="onsite-mode"><header><button type="button" onClick={() => setOnsite(false)}>← 退出现场模式</button><span>{activeStep + 1} / {onsiteSteps.length}</span></header><section><p className="eyebrow">{guide.title}</p><h1>{step.title}</h1><p>{step.body}</p>{step.nodeId && <button type="button" onClick={() => { setOnsite(false); setSelectedId(step.nodeId!); setTimeout(() => document.getElementById('spatial')?.scrollIntoView(), 0); }}>查看空间资料</button>}</section><footer><button type="button" disabled={activeStep === 0} onClick={() => setActiveStep((value) => value - 1)}>上一步</button><button type="button" disabled={activeStep === onsiteSteps.length - 1} onClick={() => setActiveStep((value) => value + 1)}>下一步</button></footer></main>; }
  return <main className="guide-page"><SiteNav/><section className="guide-hero"><GuideCover media={guide.hero} role="hero"/><div className="hero-shade"/><div><p className="eyebrow">{guide.city} · {guide.category} · {guide.tier === 'major' ? '重点章节' : '完整章节'}</p><h1>{guide.title}</h1><p className="original-title">{guide.originalTitle}</p><p>{guide.deck}</p><div className="guide-hero-actions"><a href="#orientation">开始阅读 ↓</a><button type="button" onClick={() => { setActiveStep(0); setOnsite(true); }}>进入现场模式</button></div></div></section>
    <nav className="chapter-nav" aria-label="本章目录"><a href="#orientation">定位</a><a href="#visit-scope">外观／内部</a><a href="#spatial">空间</a><a href="#sequence">顺序</a><a href="#highlights">解读</a><a href="#practical">实用</a><a href="#sources">来源</a></nav>
    <section className="guide-overview content-band" id="orientation"><div><p className="eyebrow">Orientation</p><h2>先知道自己在看什么</h2><p>{guide.overview}</p></div><div className="orientation-grid">{guide.orientation.map((item, index) => <article key={item.title}><span>{String(index + 1).padStart(2, '0')}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
    <section className="visit-scope content-band" id="visit-scope"><header className="section-heading"><p className="eyebrow">Exterior & interior</p><h2>先看外观，再进入内部</h2><p>把抵达、建筑外部和内部／场内参观分开；没有室内空间的景点明确说明，不用虚构建筑内部。</p></header><div className="visit-chapter-grid">{guide.visitChapters.map((chapter) => <article key={chapter.id} id={`visit-${chapter.id}`}><figure><img src={chapter.image.src} alt={chapter.image.alt} loading="lazy"/><figcaption>{chapter.image.caption}</figcaption></figure><div><p className="eyebrow">{chapter.label}</p><h3>{chapter.title}</h3><p>{chapter.summary}</p><h4>现场按这几步看</h4><ol>{chapter.checkpoints.map((checkpoint) => <li key={checkpoint}>{checkpoint}</li>)}</ol><p className="access-note"><strong>进入边界</strong>{chapter.accessNote}</p></div></article>)}</div></section>
    <GuideSpatial guide={guide} selectedId={selectedId} onSelect={setSelectedId} locateRequest={locateRequest}/>
    <section className="sequence-band" id="sequence"><header className="section-heading"><p className="eyebrow">Interpretive sequence</p><h2>现场顺序，不冒充导航</h2><p>按理解递进组织；入口、开放与真实走法服从现场。</p></header><div className="sequence-list">{guide.sequence.map((item, index) => <button type="button" key={`${item.title}-${index}`} className={item.nodeId === selectedId ? 'active' : ''} onClick={() => { if (item.nodeId) { setSelectedId(item.nodeId); setLocateRequest(n=>n+1); } document.getElementById('spatial')?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' }); }}><strong>{item.title}</strong><span>{item.body}</span></button>)}</div></section>
    <section className="highlights content-band" id="highlights"><header className="section-heading"><p className="eyebrow">Field notes</p><h2>{guide.highlights.length} 条对象级现场解读</h2><label className="search"><span>搜索本章</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索对象、空间或观察方法"/></label></header><div className="highlight-grid">{visible.map((item) => <article key={item.id} id={`object-${item.id}`}><button type="button" className="image-button" onClick={() => setViewer(item)} aria-label={`放大${item.title}图片`}><img src={item.image.src} alt={item.image.alt} loading="lazy"/></button><div><p className="eyebrow">{item.location} · {item.period}</p><h3>{item.title}</h3><p>{item.summary}</p><h4>为什么重要</h4><p>{item.whyItMatters}</p><h4>现场看什么</h4><p>{item.lookFor}</p><div className="object-actions">{hasInteractiveNodeBinding(guide.spatial, item.nodeId) && <button type="button" onClick={() => { setSelectedId(item.nodeId!); setLocateRequest(n=>n+1); document.getElementById('spatial')?.scrollIntoView(); }}>在景点地图中定位 ↑</button>}<a href={`#object-${item.id}`}>复制深链接 #</a></div><small>{item.image.caption}</small></div></article>)}</div></section>
    <section className="practical-band" id="practical"><header><p className="eyebrow">Practical / checked 2026-09-16</p><h2>临行前必须再核对</h2></header><ol>{guide.practical.map((item) => <li key={item}>{item}</li>)}</ol><p className="evidence-note">空间交付：{spatialDeliveryLabel(guide)}。{guide.spatial.evidenceNote}</p></section>
    <section className="sources-band" id="sources"><header><p className="eyebrow">Sources & integrity</p><h2>本章使用的公开来源</h2></header><div>{sources.map((source) => <article key={source!.id}><strong>{source!.title}</strong><span>{source!.publisher} · {source!.authority}</span>{source!.url ? <a href={source!.url} target="_blank" rel="noreferrer">打开原始页面 ↗</a> : <small>{source!.note}</small>}</article>)}</div><CoverCredit media={guide.hero}/><p>本地媒体逐图授权记录：<a href={assetUrl("/images/guides/media-manifest.json")} target="_blank" rel="noreferrer">media-manifest.json</a></p></section>{viewer && <ImageViewer item={viewer} onClose={() => setViewer(null)}/>}<Footer/></main>;
}
